package-lock.json, package.json
Update information in package.json.
=> chore: Update package.json

package-lock.json, package.json
Dependencies are updated, and the vulnerability of lodash is fixed.
=> build: update node dependencies

content/en/_index.html
I've tried to fix some language mistakes I've found on the home page of CPEditor.
I may have missed some errors, and It's also possible that I made some other mistakes in the process. 
In any of the above cases, I would be glad someone pointed them out and/or corrected them.
For now, I've only changed _index.html
I also changed some parts due to stylistic preference.
Have a nice day, and thanks for creating this editor. :)
=> Fix some errors in _index.html

.gitignore, content/en/docs/Components/Main Window/Code Editor/_index.md, content/en/docs/Components/Main Window/Menu Bar/Actions/_index.md, content/en/docs/Components/Main Window/Menu Bar/Edit/_index.md, content/en/docs/Components/Main Window/Menu Bar/File/_index.md, content/en/docs/Components/Main Window/Menu Bar/Help/_index.md, content/en/docs/Components/Main Window/Menu Bar/Options/_index.md, content/en/docs/Components/Main Window/Menu Bar/View/_index.md, content/en/docs/Components/Main Window/Menu Bar/_index.md, content/en/docs/Components/Main Window/Message Logger/_index.md, content/en/docs/Components/Main Window/Tab Bar/_index.md, content/en/docs/Components/Main Window/Test Cases/_index.md, content/en/docs/Components/Main Window/_index.md, content/en/docs/Components/Preferences/_index.md, content/en/docs/Components/_index.md, content/en/docs/FAQ/_index.md, content/en/docs/Features/_index.md, content/en/docs/Preferences/Actions.md, content/en/docs/Preferences/Advanced.md, content/en/docs/Preferences/Appearance.md, content/en/docs/Preferences/Code Edit.md, content/en/docs/Preferences/Extensions.md, content/en/docs/Preferences/File Path.md, content/en/docs/Preferences/General.md, content/en/docs/Preferences/Key Bindings.md, content/en/docs/Preferences/Language.md, content/en/docs/Preferences/_index.md, content/en/docs/Setup/_index.md
The preferences can cover most features, so it's good to write documentation for it instead of "Components" and "Features".
=> feat: add documentation for preferences

static/js/api/download.js
=> fix(download.js): improve bestAssetForPlatform

content/en/docs/Installation/Build from AUR/_index.md, content/en/docs/Installation/Build from source/_index.md, content/en/docs/Installation/Install from binaries/_index.md, content/en/docs/Installation/Use Artifacts/_index.md, content/en/docs/Setup/_index.md, content/ru/docs/Installation/Build from AUR/_index.md, content/ru/docs/Installation/Build from source/_index.md, content/ru/docs/Installation/Install from binaries/_index.md, content/ru/docs/Installation/Use Artifacts/_index.md, content/ru/docs/Setup/_index.md, content/zh/docs/Installation/Build from AUR/_index.md, content/zh/docs/Installation/Build from source/_index.md, content/zh/docs/Installation/Install from binaries/_index.md, content/zh/docs/Installation/Use Artifacts/_index.md, content/zh/docs/Setup/_index.md
Add Chinese translation of installaion.
Some translations refer to old doc deleted in https://github.com/cpeditor/cpeditor/pull/615
=> feat(installation): update docs and add Chinese translation

build.sh
So that the "Edit this page" buttons link to the correct branch.
=> build: update github_branch config in version branches

.github/workflows/build-test.yml, .github/workflows/deploy.yml
The build test was run on the hugo branch, so it didn't check PRs.
Now build test only runs on PRs and deploy runs on push.
In the build test, the PR will be merged locally.
=> ci: fix build test on pull requests

content/docs/Preferences/Extensions/_index.md, content/docs/Preferences/Extensions/_index.ru.md, content/docs/Preferences/Extensions/_index.zh.md, content/docs/Setup/_index.md, content/docs/Setup/_index.ru.md, content/docs/Setup/_index.zh.md
This PR  adds docs related to https://github.com/cpeditor/cpeditor/pull/640
=> feat(YAPF Formatter): Add Setup and docs 

.github/workflows/misspell-fixer.yml, .github/workflows/remark-lint.yml
Bump create-pull-request from v2 to v3.4.1
=> chore: bump create-pull-request from v2 to v3.4.1

content/docs/preferences/actions/_index.md, content/docs/preferences/actions/_index.ru.md, content/docs/preferences/actions/_index.zh.md, content/docs/preferences/extensions/_index.md, content/docs/preferences/extensions/_index.ru.md, content/docs/preferences/extensions/_index.zh.md, content/docs/preferences/file-path/_index.md, content/docs/preferences/file-path/_index.ru.md, content/docs/preferences/file-path/_index.zh.md
=> feat(Prefernces): make the headings the same as the preferences window

content/docs/source-code/_index.md, content/docs/source-code/_index.ru.md, content/docs/source-code/_index.zh.md
It's not very useful and should be in the CONTRIBUTING file.
=> chore: remove docs/source-code

README.md
https://github.com/sourcerer-io/sourcerer-app/issues/632
=> docs(README): remove hall of fame

.github/workflows/build-test.yml, .github/workflows/deploy.yml, .gitignore, .htmltest.yml, content/docs/preferences/extensions/_index.md, content/docs/preferences/extensions/_index.ru.md, content/docs/preferences/extensions/_index.zh.md, content/docs/setup/_index.md, content/docs/setup/_index.ru.md, content/docs/tips/_index.zh.md
=> ci: use htmltest

content/_index.html, content/_index.ru.html, content/_index.zh.html, content/download/_index.html, content/download/_index.ru.html, content/download/_index.zh.html, static/js/download.js, static/js/index.js
It seems that we can't reliably detect 64-bit or 32-bit Windows: https://stackoverflow.com/questions/1741933/detect-64-bit-or-32-bit-windows-from-user-agent-or-javascript
This closes #121.
=> feat(download): update download to adapt the new release assets

build.sh
```
v6.11
v6.10
v6.9
v6.8
```
instead of
```
v6.10
v6.11
v6.8
v6.9
```
=> build: reverse versions

config.toml, content/download/_index.html, static/js/download.js
Send some anonymous data to Google Analytics on download.
=> feat(download): add Google Analytics events

content/download/_index.ru.html, content/download/_index.zh.html
=> feat(ru,zh/download): trigger GA events on download

content/docs/preferences/extensions/_index.zh.md, content/docs/setup/_index.zh.md
Now all Chinese translation work has been done! 🥳
=> feat(setup,extensions): add Chinese translation

content/docs/preferences/code-edit/_index.md, content/docs/preferences/code-edit/_index.ru.md, content/docs/preferences/code-edit/_index.zh.md
Linked to: https://github.com/cpeditor/cpeditor/pull/795
=> docs: Add information about cursor width

content/download/_index.html
there's a translation mistake in this html.
=> fix(download): "Installation instructions" instead of "Install instructions"

content/about/_index.ru.html
For ru reviewers:
Возможно стоит заменить "Изучить Особенности" на "Изучить Преимущества", скажите своё мнение.
=> feat(about): add ru translations

content/download/_index.html, content/download/_index.ru.html, content/download/_index.zh.html
avoidwork/filesize.js#133
54.32MB => 54.3MB
123.45MB => 123MB
1.37GB => 1.37GB
=> feat(download): use significant figures to display file size

config.toml, content/community/_index.md, content/community/_index.ru.md, content/community/_index.zh.md
This resolves #180. @DanMax03 you can translate now or later.
=> feat: localize the Community page

content/docs/preferences/general/_index.md, content/docs/preferences/general/_index.ru.md, content/docs/preferences/general/_index.zh.md, content/docs/preferences/general/_index.zh_tw.md
https://github.com/cpeditor/cpeditor/pull/1308
=> fix(preferences/general): change app name "CP Editor" -> "cpeditor"
